### PR TITLE
Add blog on "Writing production grade code"

### PR DESCRIPTION
**Pull request by shreyasbapat**
## Type of PR

- [x] Blog/Article
- [ ] Feature/Enhancement
- [ ] Bug Fix

## Description

Add Blog on how to write and publish production grade code for open-source contribution and how to distribute it.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `devbae-blog/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by aroralakshya** [comment]
We'll review and get back.

**Comment by aashish-ak** [comment]
Hey @shreyasbapat, Awesome Blog. Corrected a few grammatical mistakes and linting errors. Please have a look at it once, then we'll merge.

**Comment by shreyasbapat** [comment]
Makes sense to me!

**Comment by shreyasbapat** [comment]
I didn't highlight all the code snippets as python because not all are, but you can merge it :D

**Pull request merged**
